# Generated by Django 5.1.7 on 2025-11-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_blingo_plays_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bronze_case_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gold_case_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='silver_case_balance',
            field=models.IntegerField(default=0),
        ),
    ]
