# Generated by Django 5.1.7 on 2025-11-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_bronze_case_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bronze_case_balance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gold_case_balance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='silver_case_balance',
        ),
    ]
